/**
 * Dashboard Page Component
 * 
 * The main results page that displays the user's personalized
 * workout and diet plans generated by AI. Features include:
 * - Tabbed interface for workout and diet plans
 * - Text-to-speech functionality to read plans aloud
 * - PDF export capability
 * - Motivational quotes with refresh functionality
 * 
 * Author: Muthu Selvam
 */

import React, { useState, useEffect } from 'react';
import { useLocation } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Download, Play, Pause, Dumbbell, Utensils, RefreshCcw, Quote } from 'lucide-react';
import Loading from '../components/ui/Loading';
import { generateFitnessPlan } from '../services/aiService';
import { exportToPDF } from '../lib/pdfUtils';

// Collection of motivational quotes for user inspiration
const MOTIVATIONAL_QUOTES = [
    "Every workout brings you closer to your goals. Stay consistent, stay strong!",
    "The only bad workout is the one that didn't happen.",
    "Your body can stand almost anything. It's your mind that you have to convince.",
    "Success isn't always about greatness. It's about consistency.",
    "Don't limit your challenges. Challenge your limits.",
    "Discipline is doing what needs to be done, even if you don't want to do it."
];

function Dashboard() {
    const location = useLocation();
    const userData = location.state?.userData || {};

    // Core state management
    const [isLoading, setIsLoading] = useState(true);
    const [activeTab, setActiveTab] = useState('workout');
    const [plan, setPlan] = useState(null);

    // Text-to-speech state: 'idle', 'playing', or 'paused'
    const [speechStatus, setSpeechStatus] = useState('idle');

    // Motivation quote rotation
    const [currentQuoteIndex, setCurrentQuoteIndex] = useState(0);

    /**
     * Rotates to the next motivational quote in the list.
     */
    function showNextQuote() {
        setCurrentQuoteIndex((prevIndex) => (prevIndex + 1) % MOTIVATIONAL_QUOTES.length);
    }

    /**
     * Handles text-to-speech functionality with play/pause/resume controls.
     * Uses the Web Speech API to read the plan aloud.
     */
    function handleSpeechToggle() {
        if (!plan) return;

        // If currently playing, pause the speech
        if (speechStatus === 'playing') {
            window.speechSynthesis.pause();
            setSpeechStatus('paused');
            return;
        }

        // If paused, resume the speech
        if (speechStatus === 'paused') {
            window.speechSynthesis.resume();
            setSpeechStatus('playing');
            return;
        }

        // Build the speech text based on the active tab
        const introText = `Here is your personalized ${userData.goal} plan. Your daily calorie target is ${plan.summary.daily_calories} calories.`;

        let planDetails = "";
        if (activeTab === 'workout') {
            planDetails = "For your workouts: ";
            plan.workout_plan.forEach(day => {
                planDetails += `On ${day.day}, focus on ${day.focus}. `;
            });
        } else {
            planDetails = "For your diet: ";
            plan.diet_plan.forEach(meal => {
                planDetails += `For ${meal.meal}, have ${meal.food}. `;
            });
        }

        // Create and configure the speech utterance
        const utterance = new SpeechSynthesisUtterance(introText + " " + planDetails);
        utterance.onend = () => setSpeechStatus('idle');

        // Cancel any previous speech and start fresh
        window.speechSynthesis.cancel();
        window.speechSynthesis.speak(utterance);
        setSpeechStatus('playing');
    }

    /**
     * Fetches the fitness plan from cache or generates a new one via AI.
     * Implements caching to reduce API calls for the same user/goal combo.
     */
    async function loadFitnessPlan() {
        // Guard clause: don't proceed without user data
        if (!userData.name) {
            setIsLoading(false);
            return;
        }

        // Create a unique cache key based on user profile
        const cacheKey = `plan_${userData.name}_${userData.goal}`;
        const cachedPlan = localStorage.getItem(cacheKey);

        // If we have a cached plan, use it
        if (cachedPlan) {
            setPlan(JSON.parse(cachedPlan));
            setIsLoading(false);
            return;
        }

        // Otherwise, generate a new plan from the AI
        try {
            setIsLoading(true);
            const generatedPlan = await generateFitnessPlan(userData);
            setPlan(generatedPlan);

            // Cache the plan for future use
            localStorage.setItem(cacheKey, JSON.stringify(generatedPlan));
        } catch (error) {
            console.error("Failed to generate fitness plan:", error);
        } finally {
            setIsLoading(false);
        }
    }

    // Load the plan when the component mounts
    useEffect(() => {
        loadFitnessPlan();
    }, [userData]);

    // Show loading state while plan is being generated
    if (isLoading) {
        return <Loading />;
    }

    // Helper to determine the speech button text
    function getSpeechButtonText() {
        if (speechStatus === 'playing') return 'Pause';
        if (speechStatus === 'paused') return 'Resume';
        return 'Listen to Plan';
    }

    return (
        <div id="pdf-root" className="container mx-auto px-4 py-8">

            {/* Page Header with Actions */}
            <header className="mb-8 flex flex-col md:flex-row md:items-center justify-between gap-4">
                <div>
                    <h1 className="text-3xl font-bold">Your AI Plan</h1>
                    <p className="text-muted-foreground">
                        Customized for {userData.name || 'User'}
                    </p>
                </div>

                {/* Action Buttons - Hidden from PDF export */}
                <div className="flex space-x-3" data-html2canvas-ignore="true">
                    <button
                        onClick={loadFitnessPlan}
                        className="flex items-center space-x-2 px-4 py-2 rounded-lg bg-surface hover:bg-surface/80 border border-border transition-colors outline-none focus:ring-2 focus:ring-primary"
                    >
                        <RefreshCcw className={`w-4 h-4 ${isLoading ? 'animate-spin' : ''}`} />
                        <span>Regenerate</span>
                    </button>
                    <button
                        onClick={() => exportToPDF()}
                        className="flex items-center space-x-2 px-4 py-2 rounded-lg bg-secondary/20 text-secondary border border-secondary/50 hover:bg-secondary/30 transition-colors"
                    >
                        <Download className="w-4 h-4" />
                        <span>Export PDF</span>
                    </button>
                </div>
            </header>

            {/* Main Content Grid */}
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 p-4 bg-background">

                {/* Left Column: Profile Summary and Motivation */}
                <div className="lg:col-span-1 space-y-6" data-html2canvas-ignore="true">

                    {/* Profile Summary Card */}
                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        className="p-6 rounded-xl bg-surface/50 border border-white/5"
                    >
                        <h3 className="font-semibold text-lg mb-4">Profile Summary</h3>
                        <div className="space-y-3 text-sm text-muted-foreground">
                            <div className="flex justify-between">
                                <span>Goal</span>
                                <span className="text-foreground font-medium">{userData.goal}</span>
                            </div>
                            <div className="flex justify-between">
                                <span>Level</span>
                                <span className="text-foreground font-medium">{userData.fitnessLevel}</span>
                            </div>
                            <div className="flex justify-between">
                                <span>Diet</span>
                                <span className="text-foreground font-medium">{userData.dietPreference}</span>
                            </div>

                            {/* Macro Nutrients Display */}
                            {plan?.summary && (
                                <>
                                    <div className="flex justify-between border-t border-border pt-2 mt-2">
                                        <span>Daily Target</span>
                                        <span className="text-primary font-bold">{plan.summary.daily_calories} kcal</span>
                                    </div>
                                    <div className="grid grid-cols-3 gap-2 mt-2 text-center">
                                        <div className="bg-background rounded p-2 border border-border">
                                            <div className="text-[10px] uppercase text-muted-foreground">Protein</div>
                                            <div className="font-bold text-xs">{plan.summary.macros.protein}</div>
                                        </div>
                                        <div className="bg-background rounded p-2 border border-border">
                                            <div className="text-[10px] uppercase text-muted-foreground">Carbs</div>
                                            <div className="font-bold text-xs">{plan.summary.macros.carbs}</div>
                                        </div>
                                        <div className="bg-background rounded p-2 border border-border">
                                            <div className="text-[10px] uppercase text-muted-foreground">Fats</div>
                                            <div className="font-bold text-xs">{plan.summary.macros.fats}</div>
                                        </div>
                                    </div>
                                </>
                            )}
                        </div>
                    </motion.div>

                    {/* Daily Motivation Quote Card */}
                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: 0.2 }}
                        className="p-6 rounded-xl bg-gray-100 dark:bg-surface border border-gray-200 dark:border-white/10 shadow-sm"
                    >
                        <div className="flex justify-between items-start mb-4">
                            <div className="flex items-center space-x-2">
                                <Quote className="w-5 h-5 text-muted-foreground" />
                                <h3 className="font-semibold text-foreground">Daily Motivation</h3>
                            </div>
                            <button
                                onClick={showNextQuote}
                                className="p-1 hover:bg-surface/80 rounded-full transition-colors"
                                aria-label="Show next quote"
                            >
                                <RefreshCcw className="w-4 h-4 text-muted-foreground" />
                            </button>
                        </div>
                        <p className="italic text-foreground text-lg">
                            "{MOTIVATIONAL_QUOTES[currentQuoteIndex]}"
                        </p>
                    </motion.div>
                </div>

                {/* Right Column: Workout and Diet Plans */}
                <div className="lg:col-span-2">

                    {/* Tab Navigation */}
                    <div className="flex items-center space-x-4 mb-6 border-b border-gray-700">
                        <button
                            onClick={() => setActiveTab('workout')}
                            className={`flex items-center pb-3 px-2 border-b-2 transition-colors ${activeTab === 'workout'
                                    ? 'border-primary text-primary'
                                    : 'border-transparent text-muted-foreground hover:text-foreground'
                                }`}
                        >
                            <Dumbbell className="w-4 h-4 mr-2" /> Workout Plan
                        </button>
                        <button
                            onClick={() => setActiveTab('diet')}
                            className={`flex items-center pb-3 px-2 border-b-2 transition-colors ${activeTab === 'diet'
                                    ? 'border-secondary text-secondary'
                                    : 'border-transparent text-muted-foreground hover:text-foreground'
                                }`}
                        >
                            <Utensils className="w-4 h-4 mr-2" /> Diet Plan
                        </button>
                    </div>

                    {/* Tab Content */}
                    <div className="min-h-[400px]">

                        {/* Workout Plan Tab */}
                        {activeTab === 'workout' && (
                            <motion.div
                                initial={{ opacity: 0, x: 20 }}
                                animate={{ opacity: 1, x: 0 }}
                                className="space-y-4"
                            >
                                {/* Intro Card with Speech Button */}
                                <div className="bg-surface/30 p-4 rounded-lg border border-white/5">
                                    <p className="text-muted-foreground mb-4">
                                        Your {userData.goal} journey starts here. We've customized this {userData.fitnessLevel} plan for {userData.location} workouts.
                                    </p>
                                    <button
                                        onClick={handleSpeechToggle}
                                        className="flex items-center text-sm text-primary hover:underline"
                                    >
                                        {speechStatus === 'playing' ? <Pause className="w-4 h-4 mr-1" /> : <Play className="w-4 h-4 mr-1" />}
                                        {getSpeechButtonText()}
                                    </button>
                                </div>

                                {/* Workout Days List */}
                                {plan.workout_plan.map((day, dayIndex) => (
                                    <div
                                        key={dayIndex}
                                        className="p-4 rounded-lg bg-surface border border-border hover:border-primary/50 transition-colors cursor-pointer group"
                                    >
                                        <div className="flex justify-between items-center mb-2">
                                            <h4 className="font-bold text-lg">{day.day}</h4>
                                            <span className="text-xs bg-primary/20 text-primary px-2 py-1 rounded">
                                                {day.focus}
                                            </span>
                                        </div>
                                        <ul className="space-y-1 ml-4 text-muted-foreground list-disc">
                                            {day.exercises.map((exercise, exerciseIndex) => (
                                                <li key={exerciseIndex} className="group-hover:text-foreground transition-colors">
                                                    <span className="font-medium">{exercise.name}</span> - {exercise.sets}x{exercise.reps}
                                                    <p className="text-xs italic opacity-70">{exercise.tips}</p>
                                                </li>
                                            ))}
                                        </ul>
                                    </div>
                                ))}
                            </motion.div>
                        )}

                        {/* Diet Plan Tab */}
                        {activeTab === 'diet' && (
                            <motion.div
                                initial={{ opacity: 0, x: 20 }}
                                animate={{ opacity: 1, x: 0 }}
                                className="space-y-4"
                            >
                                {/* Diet Intro Card */}
                                <div className="bg-surface/30 p-4 rounded-lg border border-white/5">
                                    <p className="text-muted-foreground">
                                        Personalized {userData.dietPreference} meal plan to achieve your {userData.goal} target of {plan.summary.daily_calories} calories.
                                    </p>
                                </div>

                                {/* Meals List */}
                                {plan.diet_plan.map((meal, mealIndex) => (
                                    <div
                                        key={mealIndex}
                                        className="p-4 rounded-lg bg-surface border border-border flex flex-col md:flex-row md:items-center justify-between hover:border-secondary/50 transition-colors cursor-pointer"
                                    >
                                        <div className="flex-1">
                                            <div className="flex items-center space-x-2 mb-1">
                                                <span className="text-xs uppercase tracking-wider text-muted-foreground">
                                                    {meal.meal}
                                                </span>
                                                <span className="text-xs font-mono text-secondary">
                                                    P: {meal.protein} | C: {meal.carbs} | F: {meal.fats}
                                                </span>
                                            </div>
                                            <h4 className="font-medium text-lg">{meal.food}</h4>
                                        </div>
                                        <span className="mt-2 md:mt-0 text-sm font-bold text-secondary bg-secondary/10 px-3 py-1 rounded-full">
                                            {meal.calories} kcal
                                        </span>
                                    </div>
                                ))}
                            </motion.div>
                        )}
                    </div>
                </div>
            </div>

            {/* Hidden Container for PDF Export */}
            {/* This container renders both workout and diet plans for printing */}
            {plan && (
                <div
                    id="pdf-export-container"
                    className="fixed top-0 left-[-9999px] w-[210mm] min-h-[297mm] bg-white text-black p-8 font-sans"
                >
                    {/* PDF Header */}
                    <div className="mb-8 border-b pb-4">
                        <h1 className="text-3xl font-bold text-sky-900 mb-2">
                            Fitness Plan for {userData.name}
                        </h1>
                        <div className="flex space-x-6 text-sm text-gray-600">
                            <span><strong>Goal:</strong> {userData.goal}</span>
                            <span><strong>Level:</strong> {userData.fitnessLevel}</span>
                            <span><strong>Diet:</strong> {userData.dietPreference}</span>
                        </div>
                    </div>

                    {/* Daily Targets Summary */}
                    <div className="mb-8">
                        <h2 className="text-xl font-bold text-gray-800 mb-4">Daily Targets</h2>
                        <div className="grid grid-cols-4 gap-4 text-center">
                            <div className="p-3 bg-sky-50 rounded-lg border border-sky-100">
                                <div className="text-xs text-sky-600 uppercase">Calories</div>
                                <div className="font-bold text-lg">{plan.summary.daily_calories}</div>
                            </div>
                            <div className="p-3 bg-gray-50 rounded-lg border border-gray-200">
                                <div className="text-xs text-gray-500 uppercase">Protein</div>
                                <div className="font-bold">{plan.summary.macros.protein}</div>
                            </div>
                            <div className="p-3 bg-gray-50 rounded-lg border border-gray-200">
                                <div className="text-xs text-gray-500 uppercase">Carbs</div>
                                <div className="font-bold">{plan.summary.macros.carbs}</div>
                            </div>
                            <div className="p-3 bg-gray-50 rounded-lg border border-gray-200">
                                <div className="text-xs text-gray-500 uppercase">Fats</div>
                                <div className="font-bold">{plan.summary.macros.fats}</div>
                            </div>
                        </div>
                    </div>

                    {/* Workout Plan Section for PDF */}
                    <div className="mb-8">
                        <h2 className="text-2xl font-bold text-sky-700 mb-4 border-b border-sky-200 pb-2">
                            Workout Plan
                        </h2>
                        <div className="space-y-6">
                            {plan.workout_plan.map((day, index) => (
                                <div key={index} className="break-inside-avoid">
                                    <h3 className="font-bold text-lg text-gray-900 mb-2">
                                        {day.day} <span className="text-sky-600 font-normal">- {day.focus}</span>
                                    </h3>
                                    <ul className="list-disc pl-5 space-y-1 text-sm text-gray-700">
                                        {day.exercises.map((exercise, exIndex) => (
                                            <li key={exIndex}>
                                                <span className="font-semibold">{exercise.name}</span> ({exercise.sets} sets x {exercise.reps})
                                                <span className="text-gray-500 ml-1">- {exercise.tips}</span>
                                            </li>
                                        ))}
                                    </ul>
                                </div>
                            ))}
                        </div>
                    </div>

                    {/* Diet Plan Section for PDF */}
                    <div className="break-before-page">
                        <h2 className="text-2xl font-bold text-indigo-700 mb-4 border-b border-indigo-200 pb-2">
                            Diet Plan
                        </h2>
                        <div className="space-y-4">
                            {plan.diet_plan.map((meal, index) => (
                                <div
                                    key={index}
                                    className="p-4 bg-gray-50 rounded-lg border border-gray-200 break-inside-avoid flex justify-between items-start"
                                >
                                    <div>
                                        <div className="font-bold text-gray-900">{meal.meal}</div>
                                        <div className="text-gray-800 my-1">{meal.food}</div>
                                        <div className="text-xs text-gray-500 font-mono">
                                            P: {meal.protein} | C: {meal.carbs} | F: {meal.fats}
                                        </div>
                                    </div>
                                    <span className="text-indigo-600 font-bold bg-indigo-50 px-2 py-1 rounded text-xs">
                                        {meal.calories} kcal
                                    </span>
                                </div>
                            ))}
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
}

export default Dashboard;
